# Generated by Django 4.2.7 on 2025-07-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_items', models.PositiveIntegerField(default=1)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('registration_deadline', models.DateTimeField()),
                ('matching_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('matching', 'Matching in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mystery Box',
                'verbose_name_plural': 'Mystery Boxes',
                'db_table': 'mystery_boxes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MysteryBoxParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('match_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mystery Box Participant',
                'verbose_name_plural': 'Mystery Box Participants',
                'db_table': 'mystery_box_participants',
            },
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_type', models.CharField(choices=[('item_swap', 'Item for Item'), ('point_redemption', 'Point Redemption'), ('mystery_box', 'Mystery Box')], default='item_swap', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('points_used', models.PositiveIntegerField(default=0)),
                ('request_message', models.TextField(blank=True)),
                ('response_message', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('shipping_info', models.JSONField(blank=True, default=dict)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Swap',
                'verbose_name_plural': 'Swaps',
                'db_table': 'swaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwapFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField(blank=True)),
                ('item_condition_rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('communication_rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('shipping_rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Swap Feedback',
                'verbose_name_plural': 'Swap Feedback',
                'db_table': 'swap_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwapMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Swap Message',
                'verbose_name_plural': 'Swap Messages',
                'db_table': 'swap_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
