# Generated by Django 4.2.7 on 2025-07-12 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swapmessage',
            name='swap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='swaps.swap'),
        ),
        migrations.AddField(
            model_name='swapfeedback',
            name='reviewed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swapfeedback',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swapfeedback',
            name='swap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='swaps.swap'),
        ),
        migrations.AddField(
            model_name='swap',
            name='offered_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_offers', to='items.item'),
        ),
        migrations.AddField(
            model_name='swap',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swap',
            name='requested_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='items.item'),
        ),
        migrations.AddField(
            model_name='swap',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mysteryboxparticipant',
            name='items',
            field=models.ManyToManyField(related_name='mystery_box_entries', to='items.item'),
        ),
        migrations.AddField(
            model_name='mysteryboxparticipant',
            name='matched_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mystery_box_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mysteryboxparticipant',
            name='mystery_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='swaps.mysterybox'),
        ),
        migrations.AddField(
            model_name='mysteryboxparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='swapfeedback',
            unique_together={('swap', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='swap',
            index=models.Index(fields=['requester', 'status'], name='swaps_request_017114_idx'),
        ),
        migrations.AddIndex(
            model_name='swap',
            index=models.Index(fields=['owner', 'status'], name='swaps_owner_i_528f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='swap',
            index=models.Index(fields=['requested_item'], name='swaps_request_19407a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mysteryboxparticipant',
            unique_together={('mystery_box', 'user')},
        ),
    ]
