# Generated by Django 4.2.7 on 2025-07-12 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_initial'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraluse',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='referrer_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_referral', to='points.pointtransaction'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointsredemption',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointsredemption',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='items.item'),
        ),
        migrations.AddField(
            model_name='pointsredemption',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redemption', to='points.pointtransaction'),
        ),
        migrations.AddField(
            model_name='pointsredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='referraluse',
            unique_together={('referral_code', 'referred_user')},
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', 'created_at'], name='point_trans_user_id_7622fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['transaction_type'], name='point_trans_transac_c2dc83_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsredemption',
            index=models.Index(fields=['user', 'status'], name='points_rede_user_id_1f3117_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsredemption',
            index=models.Index(fields=['item'], name='points_rede_item_id_924d57_idx'),
        ),
    ]
